- src/git/git.go
- src/in/in.go
Doing this in preparation for `access_token` passed to the pull command. Don't write them to disk:
https://blog.github.com/2012-09-21-easier-builds-and-deployments-using-git-over-https-and-oauth/
> Use git init/pull instead of clone to keep creds secure

- Makefile
- README.md
When the repo was renamed, the new name for the docker image is `teliaoss/github-pr-resource` but there were a couple of references to it as `telia-oss/github-pr-resource` which doesn't exist.
The purpose of this PR is to correct that.
> correcting names for docker hub location for the image

- github.go
This was not fixed in the switch from Global ID's in version, to using the PR number and commit SHA. 
Since I could not find a way to use the Github V4 API to this without having the Global ID of the PR (and I don't want to do another API call to figure it out, or to put the Global ID in the metadata or similar), I decided to use the Github V3 API instead since it only requires the PullRequest number.
> Fix put comment.

- README.md
- in.go
- in_test.go
> Add skip_download parameter to get.

- in.go
- in_test.go
Ref: https://github.com/telia-oss/github-pr-resource/issues/32#issuecomment-422955303
> Make skip_download a boolean instead of string

- README.md
- check.go
- check_test.go
- models.go
Ref #37 - for consistency we should use true boolean values wherever possible. I'm not sure why I opted for boolean parseable string to begin with 🤷‍♂️
> Make disable_ci_skip a boolean instead of string

- e2e/e2e_test.go
- git.go
- in.go
- in_test.go
- mocks/mock_git.go
- out_test.go
Ref #35 - Using `git clone` and specifying the base branch should ensure that the target branch for the PR is available locally when we run `rev-parse`. In effect, I don't think the previous implementation has ever supported non-master bases.
I've added an E2E test which reproduces the reported error, and does not complain when run against the code in this PR. So hopefully it is fixed 🤞
> Use git clone instead of git pull to support non-master bases

- models.go
Closes #44 - i.e., it is a bug fix which will be a breaking change for anyone who might have figured out that `paths` and `ignore_paths` (as documented) did nothing, while `path` and `ignore_path` should have worked 😂
> Fix mismatch between documented and implemented paths/ignore paths

- README.md
- e2e/e2e_test.go
- git.go
- github.go
- mocks/mock_git.go
- models.go
Ref #42 - this PR adds `skip_ssl_verification` to the source configuration. I have not verified that this actually works, other than that it does not break regular functionality - will need someone to test this on their own GHE with an untrusted certificate.
> Add skip ssl param

- e2e/e2e_test.go
- in.go
- in_test.go
Ref #54 - this PR adds the branch names to the metadata shown in Concourse, and the `metadata.json` file which is available to subsequent tasks.
> Added branch names (base/head ref name) to metadata

- README.md
- check.go
- check_test.go
- in_test.go
- models.go
- out_test.go
Implement the `disable_forks` parameter, which stops the resource from triggering if the pull request's repository is different from the resource's repository.
For more information search for `isCrossRepository` on [GitHub's API documentation](https://developer.github.com/v4/object/pullrequest/)
I would like to be able to configure the resource to only trigger on pull requests using branches rather than forks. This is so we can use GitHub's collaborator/team permissions instead of doing an author validation step in a task.
This pull request does not implement an end to end test for this functionality, just a unit test. Personally I think that an end-to-end test would just be testing GitHub's implementation.
Please let me know if there is further work that you require before considering …
> Feature request: disable_forks parameter

- Dockerfile
- README.md
- git.go
- in.go
- in_test.go
- mocks/mock_git.go
- models.go
- scripts/install_git_crypt.sh
Resolves #67 
This PR adds support for [git-crypt](https://www.agwa.name/projects/git-crypt/), to better align with the official git resource.
I've added a `git_crypt_key` source configuration param, that - when provided - will cause the repo to be unlocked using `git-crypt` during the `get` step.
Apart from the unit tests, I would like to include e2e tests but I didn't find an obvious way to do it, since the repo used by the tests is archived. However, I've tested this in a personal pipeline at https://concourse.our.buildo.io/teams/buildo/pipelines/gitcrypt
Notice how [build 3](https://concourse.our.buildo.io/teams/buildo/pipelines/gitcrypt/jobs/test/builds/3) (which lacks the `git_crypt_key` parameter) prints the encrypted content of the file, while [build …
> Add support for git-crypt

- git.go
`ioutil.WriteFile` can return an error, we should check it.
> Fix unhandled error in GitCryptUnlock

- scripts/install_git_crypt.sh
Fixes #87 
In my previous PR (#70) I've accidentally increased the size of the Docker image, by not cleaning up build dependencies properly.
This PR fixes it, making git-crypt adding only 6.25MB (instead of 151MB) in size.
Before this PR:
```
❯ docker history 371436e62541
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
371436e62541        6 seconds ago       /bin/sh -c #(nop)  LABEL MAINTAINER=telia-oss   0B
157a1781690f        6 seconds ago       /bin/sh -c ./install_git_crypt.sh && rm ./in…   151MB
73a96fb7985a        24 seconds ago      /bin/sh -c #(nop) ADD file:be794c3b86c757fb2…   445B
26d8ad33d89c        16 minutes ago      /bin/sh -c apk add --update --no-cache     g…   34.3MB
f4d36fcc7ee4        16 minutes ago …
```
> Cleanup git-crypt build dependnecies more aggressively

- README.md
- fakes/fake_github.go
- github.go
- models.go
- out.go
- out_test.go
The aim of this PR is to bring some interesting features of the [original version](https://github.com/jtarchie/github-pullrequest-resource), in which this repo is inspired, to this new version. 
As a regular users, we still use the previous one because we have to configure our concourse_url, context and description in most of our pipelines.
This PR also adds environment vars interpolation in the comments and target_url params.
It should resolve this issue too: https://github.com/telia-oss/github-pr-resource/issues/77 and it is backwards compatible.
Closes #77
> Add new configuration options: base_context, target_url, interpolation env var

- github.go
If we provide the target url, such as:
`https://ci.example.com/projects/project1/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_ID`
I think we don't need to concatenate the `builds/BUILD_ID` again, we can trust with the given target url.
What do you think?
Thank you 😄
> if target url is given, do not concatenate 'builds/BUILD_ID' in the url

- git.go
The `git checkout <commit>` creates a somewhat noisy log output for the `get` step:
```
<...>
Note: checking out 'd63b223'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
git checkout -b <new-branch-name>
<...>
```
This PR solves this by using a one-liner to rebase the `headSha` on top of `baseRef`.
> Clean rebase output by using oneliner

- README.md
- e2e/e2e_test.go
- fakes/fake_git.go
- git.go
- in.go
- in_test.go
Closes #106 
Adds the `git.depth` get parameter that - when set to a positive integer - causes the resource to use `git pull --depth N` to create a shallow clone of the git repo.
I've used the `git.depth` name for two reasons:
- it matches with the name the same parameter had in `https://github.com/jtarchie/github-pullrequest-resource`
- if more git-related parameter will be added in the future, they can use the same "namespacing" `git.*`
I have very little experience with Go, so no offense taken for any comment about the style :)
> Add git_depth get parameter

- e2e/e2e_test.go
- git.go
We had a couple of issues after merging #108:
- Endpoint was not being included in the `git` command when `git_depth` was set. Fixed this, and removed the repetition to avoid future mistakes.
- E2E test for depth failed since it had the wrong expectation for the length of the git history. Rewrote the test cases to allow us to test the expected length of the git history, and the commit messages/their order.
> Fix fetch depth and e2e tests

- github.go
Since yesterday all our PR status links became broken. Instead of https://ci.ourorg.com/builds/111 we started seeing https://github.com/ci.ourorg.com/builds/111
After some investigation, it turned out the problem is using `path.Join()` to concatenate strings, it replaces `https://ci...`  with a `http:/ci`. Sadly, Github API doesn't complain about it.
> Fix strings concatenation for status build url

- README.md
- e2e/e2e_test.go
- fakes/fake_git.go
- git.go
- in.go
- in_test.go
resolves #115 
Context are pretty much included in #115 .
Just thought that `checkout` would make more sense than `none` as an option for the `integrationTool`.
> Add option to have a plain checkout

- e2e/e2e_test.go
- in.go
- in_test.go
The GitHub PR resource type by jtarchie [1] created files that
contained the PR information [2].  Each file contained one piece of
information (e.g., the git branch name or the author).  This format
was convenient since many resource types are configured by passing the
name of a file that contains the option's value.  For example, the
`tag_file` option of the Docker Image resource type accepts the name
of a file whose content is the desired tag [3].
The telia-oss GitHub resource type puts all the PR information in a
single file, metadata.json.  To extract data from this file, it's
necessary to create a new task.
This commit modifies `in.go` so that each individual PR information is
also written into its own file.  For example, `.git/resource/head_name`
contains the name of the git branch. …
> Explode metadata.json into individual files

- e2e/e2e_test.go
- in_test.go
This fixes the e2e tests for individual metadata files. I think a single test is enough since the content will be identical to `metadata.json`, which is checked in every test case. Also I did not notice the `snake_case` when merging #122 😅
> Fix metadata files e2e test

- README.md
Update to use correct value from
https://concourse-ci.org/implementing-resource-types.html#resource-metadata
> Fix environment variable name in README

- out.go
- out_test.go
List of env vars: https://concourse-ci.org/implementing-resource-types.html#resource-metadata
When posting code snippets as github comments, not everything that looks
like an environment variable needs to be expanded.
> Only expand concourse build metadata env vars

- README.md
- e2e/e2e_test.go
Ref #156 - this PR updates the documentation on costs, and adds a E2E test to keep track of the cost of `check` against the Github rate limit. Cost calculation needs to be verified.
> Add query cost test

- .gitignore
- .travis.yml
- Dockerfile
- go.mod
Need to stay on top of updates. Starting with Go, then our dependencies.
> Bump go version to 1.13

- e2e/e2e_test.go
- git.go
This PR primarily adds e2e testing for submodules after merging (#187), and removes the `--global` flags to avoid polluting the development environment when running e2e tests. I have also replaced [github-pr-resource-e2e](https://github.com/itsdalmo/github-pr-resource-e2e) with [test-repository-active](https://github.com/itsdalmo/test-repository-active) in e2e tests involving comments and submodules.
> Add e2e test for submodules

- README.md
It was a little hard to grok that example listed was for a `put` for pending status, hopefully grouping these closer to the text will be helpful.
> Moving example closer to text

- in.go
Fixes #210 
As suggested by @itsdalmo in the issue, this PR simply moves the code that write version and metadata to disk before the integration step.
This allow using a put step (which requires `version.json`) for reporting integration errors such as merge conflicts with the base branch
> Write version and metadata before the integration step

- git.go
Using a non-octal os.FileMode that looks like it was meant to be in octal
```go
if err := ioutil.WriteFile(keyPath, decodedKey, 600); err != nil {
return fmt.Errorf("failed to write git-crypt key to file: %s", err)
}
```
becomes 01130, where we'd typically want 600
This PR correctly implements it with the intended `os.FileMode(0600)`
```go
if err := ioutil.WriteFile(keyPath, decodedKey, os.FileMode(0600)); err != nil {
return fmt.Errorf("failed to write git-crypt key to file: %s", err)
}
```
> Fix os.FileMode was meant to be in octal.

- check.go
- check_test.go
- fakes/fake_github.go
- github.go
Ensure that the GraphQL query requests PRs matching the desired states,
rather than requesting all PRs and filtering on the client.
Fixes #233
> fix: filter pull requests on the server, not client
